# Generated by Django 2.0.3 on 2018-04-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(blank=True, choices=[('トップス', 'トップス'), ('パンツ', 'パンツ')], max_length=128, verbose_name='カテゴリ')),
                ('sub_category_1', models.CharField(blank=True, choices=[('シャツ', 'シャツ'), ('カットソー', 'カットソー')], max_length=128, verbose_name='サブカテゴリ1')),
            ],
        ),
    ]
