# Generated by Django 2.0.3 on 2018-04-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='main_category',
            field=models.CharField(blank=True, choices=[('トップス', 'トップス'), ('ジャケット/アウター', 'ジャケット/アウター'), ('パンツ', 'パンツ'), ('靴', '靴'), ('バッグ', 'バッグ'), ('スーツ', 'スーツ'), ('帽子', '帽子'), ('アクセサリー', 'アクセサリー'), ('小物', '小物'), ('時計', '時計'), ('水着', '水着'), ('レッグウェア', 'レッグウェア'), ('アンダーウェア', 'アンダーウェア'), ('その他', 'その他')], max_length=128, verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sub_category_1',
            field=models.CharField(blank=True, choices=[('シャツ', 'トップス'), ('カットソー', 'トップス'), ('ポロシャツ', 'トップス'), ('タンクトップ', 'トップス'), ('ニット/セーター', 'トップス'), ('パーカー', 'トップス'), ('カーディガン', 'トップス'), ('スウェット', 'トップス'), ('ジャージ', 'トップス'), ('ベスト', 'トップス'), ('その他', 'トップス')], max_length=128, verbose_name='サブカテゴリ1'),
        ),
    ]
