# Generated by Django 2.0.3 on 2018-04-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_auto_20180408_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='fit',
            field=models.CharField(blank=True, choices=[('細身', 'トップス'), ('普通', 'トップス'), ('ゆったり', 'トップス')], max_length=128, verbose_name='フィット'),
        ),
    ]
