# Generated by Django 2.0.3 on 2018-04-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_category_fit'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='design',
            field=models.CharField(blank=True, choices=[('細身', 'トップス'), ('普通', 'トップス'), ('ゆったり', 'トップス')], max_length=128, verbose_name='デザイン'),
        ),
    ]
