# Generated by Django 2.0.3 on 2018-04-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_category_design'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='main_category',
            field=models.CharField(blank=True, choices=[('トップス', 'メンズ'), ('ジャケット/アウター', 'メンズ'), ('パンツ', 'メンズ'), ('靴', 'メンズ'), ('バッグ', 'メンズ'), ('スーツ', 'メンズ'), ('帽子', 'メンズ'), ('アクセサリー', 'メンズ'), ('小物', 'メンズ'), ('時計', 'メンズ'), ('水着', 'メンズ'), ('レッグウェア', 'メンズ'), ('アンダーウェア', 'メンズ'), ('その他', 'メンズ')], max_length=128, verbose_name='カテゴリ'),
        ),
    ]
