# Generated by Django 2.0.3 on 2018-07-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_auto_20180728_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='design',
            field=models.CharField(blank=True, choices=[('細身', 'トップス'), ('普通', 'トップス'), ('ゆったり', 'トップス'), ('スキニー', 'パンツ'), ('スタンダード', 'パンツ'), ('ワイド', 'パンツ')], max_length=128, verbose_name='デザイン'),
        ),
        migrations.AlterField(
            model_name='category',
            name='fit',
            field=models.CharField(blank=True, choices=[('細身', 'トップス'), ('普通', 'トップス'), ('ゆったり', 'トップス'), ('スキニー', 'パンツ'), ('スタンダード', 'パンツ'), ('ワイド', 'パンツ')], max_length=128, verbose_name='フィット'),
        ),
    ]
