# Generated by Django 2.1 on 2018-08-15 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0008_auto_20180729_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='design',
        ),
        migrations.RemoveField(
            model_name='category',
            name='fit',
        ),
        migrations.RemoveField(
            model_name='category',
            name='main_category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='sub_category_1',
        ),
    ]
