# Generated by Django 2.0.3 on 2018-11-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0010_auto_20181117_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='性別')),
                ('gender', models.CharField(choices=[('メンズ', 'メンズ'), ('レディース', 'レディース')], max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='maincategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='post',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='parent',
        ),
        migrations.DeleteModel(
            name='MainCategory',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Sex',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
