# Generated by Django 2.0.3 on 2018-11-18 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0011_auto_20181118_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='メインカテゴリ名')),
                ('value', models.CharField(choices=[('トップス', 'トップス'), ('パンツ', 'パンツ'), ('スカート', 'スカート'), ('ワンピース', 'ワンピース')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('m_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.MainCategory', verbose_name='メインカテゴリ')),
            ],
        ),
        migrations.RenameField(
            model_name='gender',
            old_name='gender',
            new_name='value',
        ),
        migrations.AddField(
            model_name='maincategory',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.Gender', verbose_name='性別'),
        ),
    ]
