# Generated by Django 2.0.3 on 2018-11-18 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0012_auto_20181118_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gender',
            old_name='value',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='maincategory',
            old_name='value',
            new_name='main_category',
        ),
        migrations.RemoveField(
            model_name='gender',
            name='name',
        ),
        migrations.RemoveField(
            model_name='maincategory',
            name='name',
        ),
    ]
