# Generated by Django 2.0.3 on 2018-11-23 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0013_auto_20181118_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(choices=[('シャツ・ブラウス', 'シャツ・ブラウス'), ('カットソー', 'カットソー'), ('パーカー', '"パーカー'), ('デニムパンツ', 'デニムパンツ'), ('カーゴパンツ', 'カーゴパンツ'), ('チノパンツ', 'チノパンツ'), ('スラックス', 'スラックス'), ('スカート', 'スカート'), ('デニムスカート', 'デニムスカート'), ('ワンピース', 'ワンピース'), ('シャツワンピース', 'シャツワンピース'), ('ジャンパースカート', 'ジャンパースカート'), ('チュニック', 'チュニック'), ('ドレス', 'ドレス')], max_length=255)),
                ('gender', models.ManyToManyField(to='generator.Gender', verbose_name='性別')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.MainCategory', verbose_name='メインカテゴリ')),
            ],
        ),
    ]
