# Generated by Django 2.0.3 on 2018-11-24 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0014_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='COLLER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coller', models.CharField(choices=[('レギュラー', 'レギュラー'), ('ボタンダウン', 'ボタンダウン'), ('オープン', 'オープン'), ('スタンド', 'スタンド')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DESIGN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.CharField(choices=[('無地', '無地'), ('ボーダー', 'ボーダー'), ('ドット', 'ドット'), ('ストライプ', 'ストライプ'), ('チェック', 'チェック')], max_length=255)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.MainCategory', verbose_name='メインカテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='NECK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.CharField(choices=[('クルーネック', 'カットソー'), ('Uネック', 'カットソー'), ('Vネック', 'カットソー'), ('ボートネック', 'カットソー')], max_length=255)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.MainCategory', verbose_name='メインカテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='SILHOUETTE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('silhouette', models.CharField(choices=[('細身', '細身'), ('普通', '普通'), ('ゆったり', 'ゆったり'), ('スキニー', 'スキニー'), ('スタンダード', 'スタンダード'), ('ワイド', 'ワイド'), ('タイト', 'タイト'), ('フレア', 'フレア'), ('台形', '台形'), ('プリーツ', 'プリーツ'), ('ティアード', 'ティアード')], max_length=255)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.MainCategory', verbose_name='メインカテゴリ')),
            ],
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_category',
            field=models.CharField(choices=[('シャツ・ブラウス', 'シャツ・ブラウス'), ('カットソー', 'カットソー'), ('パーカー', 'パーカー'), ('デニムパンツ', 'デニムパンツ'), ('カーゴパンツ', 'カーゴパンツ'), ('チノパンツ', 'チノパンツ'), ('スラックス', 'スラックス'), ('スカート', 'スカート'), ('デニムスカート', 'デニムスカート'), ('ワンピース', 'ワンピース'), ('シャツワンピース', 'シャツワンピース'), ('ジャンパースカート', 'ジャンパースカート'), ('チュニック', 'チュニック'), ('ドレス', 'ドレス')], max_length=255),
        ),
        migrations.AddField(
            model_name='coller',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.SubCategory', verbose_name='サブカテゴリ'),
        ),
    ]
