# Generated by Django 2.0.3 on 2018-11-25 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0015_auto_20181124_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='gender',
        ),
    ]
