# Generated by Django 2.0.3 on 2018-11-25 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0016_remove_subcategory_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='s_category',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.PROTECT, to='generator.SubCategory', verbose_name='サブカテゴリ'),
        ),
        migrations.AddField(
            model_name='post',
            name='silhouette',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.PROTECT, to='generator.SILHOUETTE', verbose_name='シルエット'),
        ),
        migrations.AlterField(
            model_name='post',
            name='m_category',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.PROTECT, to='generator.MainCategory', verbose_name='メインカテゴリ'),
        ),
    ]
