# Generated by Django 2.0.3 on 2018-11-25 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0017_auto_20181125_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='m_category',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='generator.MainCategory', verbose_name='メインカテゴリ'),
        ),
    ]
