# Generated by Django 2.0.3 on 2018-11-25 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0018_auto_20181125_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='silhouette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.SILHOUETTE', verbose_name='シルエット'),
        ),
    ]
