# Generated by Django 2.0.3 on 2018-11-25 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0019_auto_20181125_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='m_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.MainCategory', verbose_name='メインカテゴリ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='s_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.SubCategory', verbose_name='サブカテゴリ'),
        ),
    ]
