# Generated by Django 2.0.3 on 2018-11-25 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0020_auto_20181125_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='design',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='generator.DESIGN', verbose_name='デザイン'),
        ),
    ]
