# Generated by Django 2.0.3 on 2018-11-25 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0021_post_design'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.DESIGN', verbose_name='デザイン'),
        ),
    ]
