# Generated by Django 2.0.3 on 2018-11-25 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0022_auto_20181125_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neck',
            old_name='design',
            new_name='neck',
        ),
    ]
