# Generated by Django 2.0.3 on 2018-11-25 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0023_auto_20181125_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neck',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.SubCategory', verbose_name='サブカテゴリ'),
        ),
    ]
