# Generated by Django 2.0.3 on 2018-11-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0024_auto_20181125_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neck',
            name='neck',
            field=models.CharField(choices=[('クルーネック', 'クルーネック'), ('Uネック', 'Uネック'), ('Vネック', 'Vネック'), ('ボートネック', 'ボートネック')], max_length=255),
        ),
    ]
