# Generated by Django 2.0.3 on 2018-12-02 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0025_auto_20181125_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='coller',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='generator.COLLER', verbose_name='襟'),
        ),
        migrations.AddField(
            model_name='post',
            name='neck',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='generator.NECK', verbose_name='ネック'),
        ),
    ]
