# Generated by Django 2.0.3 on 2018-12-16 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0027_auto_20181216_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_button', models.CharField(choices=[('プルオーバー', 'プルオーバー'), ('ジップアップ', 'ジップアップ')], max_length=255)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.SubCategory', verbose_name='サブカテゴリ')),
            ],
        ),
        migrations.RemoveField(
            model_name='zip_button',
            name='parent',
        ),
        migrations.AlterField(
            model_name='post',
            name='length',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.LENGTH', verbose_name='丈'),
        ),
        migrations.AlterField(
            model_name='post',
            name='zip_button',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.ZipButton', verbose_name='ジップ・ボタン'),
        ),
        migrations.DeleteModel(
            name='ZIP_BUTTON',
        ),
    ]
