# Generated by Django 2.0.3 on 2018-12-23 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0028_auto_20181216_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.CharField(choices=[('リジッド', 'リジッド'), ('ユーズド加工', 'ユーズド加工'), ('クラッシュ・ダメージ加工', 'クラッシュ・ダメージ加工')], max_length=255)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.SubCategory', verbose_name='サブカテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg', models.CharField(choices=[('テーパード', 'テーパード'), ('フレア・ブーツカット', 'フレア・ブーツカット')], max_length=255)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.SubCategory', verbose_name='サブカテゴリ')),
            ],
        ),
        migrations.AlterField(
            model_name='length',
            name='length',
            field=models.CharField(choices=[('ひざ上', 'ひざ上'), ('ひざ丈', 'ひざ丈'), ('クロップド', 'クロップド'), ('フルレングス', 'フルレングス'), ('ショート・ミニ丈', 'ショート・ミニ丈'), ('ロング・マキシ丈', 'ロング・マキシ丈'), ('ミモレ・半端丈', 'ミモレ・半端丈')], max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='length',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.Length', verbose_name='丈'),
        ),
        migrations.AddField(
            model_name='post',
            name='effect',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='generator.Effect', verbose_name='加工'),
        ),
        migrations.AddField(
            model_name='post',
            name='leg',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='generator.Leg', verbose_name='膝下'),
        ),
    ]
