# Generated by Django 2.0.3 on 2019-01-20 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0037_auto_20190120_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='silhouette',
            name='description',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='length',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.Length', verbose_name='丈'),
        ),
    ]
